const path = require('path');
const dotenv = require('dotenv');
dotenv.config({ path: path.resolve(__dirname, '.env') });

module.exports = {
  env: {
    NEXT_PUBLIC_SERVER_PROTOCOL: process.env.NEXT_PUBLIC_SERVER_PROTOCOL,
    NEXT_PUBLIC_SERVER_HOST: process.env.NEXT_PUBLIC_SERVER_HOST,

    NEXT_PUBLIC_TEST_SERVER_PROTOCOL:
      process.env.NEXT_PUBLIC_TEST_SERVER_PROTOCOL,
    NEXT_PUBLIC_TEST_SERVER_HOST: process.env.NEXT_PUBLIC_TEST_SERVER_HOST,
    NEXT_PUBLIC_TEST_SERVER_PORT: process.env.NEXT_PUBLIC_TEST_SERVER_PORT,

    NEXT_PUBLIC_APP_CLIENT_PROTOCOL:
      process.env.NEXT_PUBLIC_APP_CLIENT_PROTOCOL,
    NEXT_PUBLIC_APP_CLIENT_HOST: process.env.NEXT_PUBLIC_APP_CLIENT_HOST,
    NEXT_PUBLIC_APP_CLIENT_PORT: process.env.NEXT_PUBLIC_APP_CLIENT_PORT,

    NEXT_PUBLIC_LANDING_CLIENT_PROTOCOL:
      process.env.NEXT_PUBLIC_LANDING_CLIENT_PROTOCOL,
    NEXT_PUBLIC_LANDING_CLIENT_HOST:
      process.env.NEXT_PUBLIC_LANDING_CLIENT_HOST,
    NEXT_PUBLIC_LANDING_CLIENT_PORT:
      process.env.NEXT_PUBLIC_LANDING_CLIENT_PORT,

    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  },
};
