export enum MEMBER {
  ID = "id",
  NAME = "name",
  MOBILE_PHONE = "mobilePhone",
  PROFILE_IMAGE = "profileImage",
  BIRTH = "birth",
  IS_LUNAR = "isLunar",
  GENDER = "gender",
  ADDRESS = "address",
  DETAIL_ADDRESS = "detailAddress",
  HOME_PHONE = "homePhone",
  FAMILY_ID = "familyId",
  OCCUPATION = "occupation",
  SCHOOL = "school",
  MARRIAGE = "marriage",
  DETAIL_MARRIAGE = "detailMarriage",
  MINISTRY = "ministry",
  GROUP = "group",
  OFFICER = "officer",
  EDUCATION = "education",
  OFFICER_START_DATE = "officerStartDate",
  OFFICER_START_CHURCH = "officerStartChurch",
  BAPTISM = "baptism",
  GUIDED_BY_ID = "guidedById",
  PREVIOUS_CHURCH_NAME = "previousChurchName",
  VEHICLE_NUMBER = "vehicleNumber",
}
