export enum STATUS {
  RESERVE = 'reserve',
  IN_PROGRESS = 'inProgress',
  DONE = 'done',
  PENDING = 'pending',
}

export type VISITATION_STATUS = STATUS.RESERVE | STATUS.DONE | STATUS.PENDING;

export type TASK_STATUS =
  | STATUS.RESERVE
  | STATUS.DONE
  | STATUS.PENDING
  | STATUS.IN_PROGRESS;

export type EDUCATION_TERM_STATUS =
  | STATUS.RESERVE
  | STATUS.DONE
  | STATUS.PENDING
  | STATUS.IN_PROGRESS;

export type EDUCATION_SESSION_STATUS =
  | STATUS.RESERVE
  | STATUS.DONE
  | STATUS.PENDING;
