export enum STATUS {
  RESERVE = 'reserve',
  IN_PROGRESS = 'inProgress',
  DONE = 'done',
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  CANCELED = 'canceled',
  COMPLETED = 'completed',
  INCOMPLETE = 'incomplete',
}

export type VISITATION_STATUS = STATUS.RESERVE | STATUS.DONE | STATUS.PENDING;

export type TASK_STATUS =
  | STATUS.RESERVE
  | STATUS.DONE
  | STATUS.PENDING
  | STATUS.IN_PROGRESS;

export type EDUCATION_STATUS =
  | STATUS.RESERVE
  | STATUS.DONE
  | STATUS.PENDING
  | STATUS.IN_PROGRESS;

export type EDUCATION_TERM_STATUS =
  | STATUS.RESERVE
  | STATUS.DONE
  | STATUS.PENDING
  | STATUS.IN_PROGRESS;

export type EDUCATION_SESSION_STATUS =
  | STATUS.RESERVE
  | STATUS.DONE
  | STATUS.PENDING;

export type JOIN_REQUEST_STATUS =
  | STATUS.PENDING
  | STATUS.APPROVED
  | STATUS.REJECTED
  | STATUS.CANCELED;

// 교육 이수상태
export type EDUCATION_ENROLLMENT_STATUS =
  | STATUS.INCOMPLETE
  | STATUS.COMPLETED
  | STATUS.IN_PROGRESS;
