export const BLACK = '#111827';
export const WHITE = '#FFFFFF';

export enum GRAY {
  SUPER_LIGHT = '#f9fAfB',
  EXTRA_LIGHT = '#efefef',
  LIGHT = '#E5E7EB',
  SEMI_LIGHT = '#cfcfcf',
  DEFAULT = '#9f9f9f',
  SEMI_DARK = '#7f7f7f',
  DARK = '#6B7280',
  EXTRA_DARK = '#374151',
}

export enum MAIN {
  EXTRA_LIGHT = '#EFF6FF',
  LIGHT = '#DBEAFE',
  DEFAULT = '#2563EB',
  DARK = '#1a51cd',
}

export enum DESTRUCTIVE {
  EXTRA_LIGHT = '#FEF2F2',
  LIGHT = '#FECACA',
  DEFAULT = '#EF4444',
  DARK = '#B91C1C',
  EXTRA_DARK = '#991B1B',
}

export enum YELLOW {
  LIGHT = '#FCF9C3',
  DARK = '#854D0F',
}

export enum VIOLET {
  LIGHT = '#E0E7FF',
  DARK = '#4F46E5',
}

export enum PURPLE {
  LIGHT = '#F3E8FF',
  DARK = '#9333EA',
}

export enum ORANGE {
  LIGHT = '#FFEDD5',
  DARK = '#EA580C',
}

export enum GREEN {
  LIGHT = '#DCFCE7',
  DEFAULT = '#16A34A',
  DARK = '#1E6839',
}

export enum RED {
  LIGHT = '#FCE2E1',
  DEFAULT = '#DC2626',
  DARK = '#991B1A',
}

export enum STATUS_COLOR {
  RESERVE = '#a69f9f',
  IN_PROGRESS = '#406bff',
  DONE = '#3ae17a',
  PENDING = '#ff9926',

  COMPLETED = '#3ae17a',
  INCOMPLETE = '#f32827',

  PRESENT = '#3ae17a',
  ABSENT = '#f32827',
  UNDEFINED = WHITE,

  CANCELED = '#a69f9f',
  APPROVED = '#3ae17a',
  REJECTED = '#f32827',
}

export enum STATUS_FONT_COLOR {
  RESERVE = GRAY.DARK,
  IN_PROGRESS = MAIN.DARK,
  DONE = GREEN.DARK,
  PENDING = YELLOW.DARK,

  COMPLETED = GREEN.DARK,
  INCOMPLETE = GRAY.DARK,

  PRESENT = GREEN.DARK,
  ABSENT = RED.DARK,
  UNDEFINED = WHITE,

  CANCELED = GRAY.DARK,
  APPROVED = GREEN.DARK,
  REJECTED = RED.DARK,
}

export enum STATUS_BACKGROUND_COLOR {
  RESERVE = GRAY.LIGHT,
  IN_PROGRESS = MAIN.LIGHT,
  DONE = GREEN.LIGHT,
  PENDING = YELLOW.LIGHT,

  COMPLETED = GREEN.LIGHT,
  INCOMPLETE = GRAY.LIGHT,

  PRESENT = GREEN.LIGHT,
  ABSENT = RED.LIGHT,
  UNDEFINED = WHITE,

  CANCELED = GRAY.LIGHT,
  APPROVED = GREEN.LIGHT,
  REJECTED = RED.LIGHT,
}

export enum CALENDAR_COLOR {
  MEMBER = '#F2C94C',
  VISITATION = '#9B51E0',
  TASK = '#2F80ED',
  EDUCATION = '#EB5757',
  EVENT = '#27AE60',
  HOLIDAY = '#BDBDBD',
}
